# Nicky config - www.okicore.com

# Storage type "sqlite" or "mysql"
type: 'sqlite'

# MySQL connection settings.
host: 'localhost'
port: '3306'
user: 'root'
password: 'password'
database: 'nicky'

# Change name tags if TagAPI is installed?
tagapi: 'true'

# Should names in the tablist be updated?
tab: 'true'

# Should all nicknames be unique?
unique: 'true'