name: Nicky
main: me.nonit.nicky.Nicky
version: 0.2
description: Simple SQL nickname plugin.
author: Melonking

commands:
   nick:
      description: Set a nickname
      usage: /<command>
   delnick:
      description: Unset a nickname
      usage: /<command>

permissions:
    nicky.set:
        default: op
    nicky.set.other:
        default: op
    nicky.del:
        default: op
    nicky.del.other:
        default: op
    nicky.color:
        default: op